// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_f96EOVVwrPNLPd2qs5JYoAQdxazzgJU',
    appId: '1:535948616839:web:767f5460a68aa0a3f58422',
    messagingSenderId: '535948616839',
    projectId: 'chatapp-e203e',
    authDomain: 'chatapp-e203e.firebaseapp.com',
    storageBucket: 'chatapp-e203e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_VMvUn-ySxCZ25FcOUWF8rF_onPZZbE4',
    appId: '1:535948616839:android:934ad87b78684dd8f58422',
    messagingSenderId: '535948616839',
    projectId: 'chatapp-e203e',
    storageBucket: 'chatapp-e203e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPCQnAcoV40XJwZP7JC8kBKmA8aVabFfA',
    appId: '1:535948616839:ios:9cf2ae5a95fa4f6ef58422',
    messagingSenderId: '535948616839',
    projectId: 'chatapp-e203e',
    storageBucket: 'chatapp-e203e.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPCQnAcoV40XJwZP7JC8kBKmA8aVabFfA',
    appId: '1:535948616839:ios:920e0317c6e0fc25f58422',
    messagingSenderId: '535948616839',
    projectId: 'chatapp-e203e',
    storageBucket: 'chatapp-e203e.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
